### ISSUE TITLE
Missing Tweets in the streaming collection

### ISSUE THREAD

**Issue by sameeravithana** [gmuric/avax-tweets-dataset#3]
Hi, I used Twitter Academic Research resources and Twarc to rehydrate streaming collection tweets. But only managed to get 1.2M tweets instead of 1.8M. There were no tweets for some tweet ids in this list. Any reasons?

**Comment by lishichengyan** [comment]
Hi @SamTube405 , thanks for raising the issue. Many accounts in the streaming collection may be suspended by Twitter due to violating the community policy, that might be the reason you can not get all the tweets. You may use twitter API to verify if an account has been suspended:

For example:

```
https://api.twitter.com/2/users/:id
```

if the json object returned by this endpoint contains something like ```"error": "Not authorized."```, it means the account you are querying is not reachable anymore. Hope this helps!

**Comment by sameeravithana** [comment]
@lishichengyan Thank you. Unfortunately, I do not know the user ids for the tweet ids in the collection. But I double check few tweet ids manually, and I did not receive any information from the API.
